# Generated by Django 5.1.6 on 2025-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='url_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
